dataset:
  modality: image
  dataset_name: image_base
  data_dir: /home/ma-user/work/preliminary_grounding/z00848098/code/My_OpenSpatial/data_root/EmbodiedScan/preprocessed/arkitscenes/per_image/data-00000.parquet
  raw_data_root: /home/ma-user/work/preliminary_grounding/z00848098/code/My_OpenSpatial/data_root/EmbodiedScan/data/

pipeline:
  file_name: base_pipeline
  class_name: BasePipeline

  stages:
    filter_stage:
      -
        file_name: 3dbox_filter
        method: ThreeDBoxFilter
        proj_mask_threshold: 0.1
        box3d_pcd_threshold: 0.2
        box_scale_factor: 0.9
        mask_area_threshold: 0.005
        update_keys: []
        filter_tags: ["ceiling", "floor", "wall", "object"]
        output_dir:
        use_multi_processing: true
        num_workers: 40

    localization_stage:
      -
        file_name: sam2_refiner
        method: Sam2Refiner
        update_keys: ["obj_tags", "bboxes_3d_world_coords"]
        depends_on: filter_stage/3dbox_filter
        output_dir:
        segmenter_model: /home/ma-user/work/preliminary_grounding/z00848098/code/My_OpenSpatial/data_root/model_weights/sam2-hiera-large/
        segmenter_backend: transformers
        device: "npu:0,npu:1,npu:2,npu:3"
        replicas_per_device: 1
        use_multi_processing: true
        num_workers: 4
        batch_size: 32

    scene_fusion_stage:
      -
        file_name: depth_back_projection
        method: DepthBackProjecter
        depends_on: localization_stage/sam2_refiner
        output_dir:
        use_multi_processing: true
        num_workers: 40
